apiVersion: v1
kind: Service
metadata:
  name: my-godocs-svc
  labels:
    app: godocs
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: godocs